-- ============================================================================
-- ACM-W QuizVerse - Supabase Database Schema
-- ============================================================================
-- Instructions:
-- 1. Create a new Supabase Project at https://supabase.com
-- 2. Open the SQL Editor in your Supabase Dashboard
-- 3. Paste and run this script to create the tables, indexes, RLS policies, and seed data.
-- ============================================================================

-- 1. Table: quiz_questions
CREATE TABLE IF NOT EXISTS public.quiz_questions (
    id SERIAL PRIMARY KEY,
    category TEXT NOT NULL,
    question TEXT NOT NULL,
    options JSONB NOT NULL,
    correct_index INTEGER NOT NULL,
    explanation TEXT NOT NULL,
    difficulty TEXT NOT NULL DEFAULT 'Medium',
    tags TEXT[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Table: leaderboard
CREATE TABLE IF NOT EXISTS public.leaderboard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_name TEXT NOT NULL,
    avatar_initials TEXT NOT NULL DEFAULT 'AW',
    score INTEGER NOT NULL,
    accuracy INTEGER NOT NULL,
    time_taken_seconds INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Indexes for high-performance sorting
CREATE INDEX IF NOT EXISTS idx_leaderboard_rank 
ON public.leaderboard (score DESC, time_taken_seconds ASC);

CREATE INDEX IF NOT EXISTS idx_quiz_questions_category 
ON public.quiz_questions (category);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.quiz_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leaderboard ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policies:
-- Allow anyone (anonymous or authenticated) to read quiz questions
DROP POLICY IF EXISTS "Public can read questions" ON public.quiz_questions;
CREATE POLICY "Public can read questions" 
ON public.quiz_questions FOR SELECT 
TO public 
USING (true);

-- Allow anyone to read the leaderboard
DROP POLICY IF EXISTS "Public can view leaderboard" ON public.leaderboard;
CREATE POLICY "Public can view leaderboard" 
ON public.leaderboard FOR SELECT 
TO public 
USING (true);

-- Allow anyone to submit their score to the leaderboard
DROP POLICY IF EXISTS "Public can submit scores" ON public.leaderboard;
CREATE POLICY "Public can submit scores" 
ON public.leaderboard FOR INSERT 
TO public 
WITH CHECK (true);

-- ============================================================================
-- 6. Seed Questions Dataset
-- ============================================================================
INSERT INTO public.quiz_questions (id, category, question, options, correct_index, explanation, difficulty, tags)
VALUES
(
    1,
    'ACM-W',
    'What does ACM-W primarily focus on within the global computing community?',
    '["Supporting, celebrating, and advocating for women in computing", "Selling discounted hardware to engineering students", "Certifying proprietary programming language compilers", "Managing intercollegiate sports tournaments"]'::jsonb,
    0,
    'ACM-W supports, celebrates, and advocates internationally for the full engagement of women in all aspects of the computing field, providing a wide range of programs and services to members.',
    'Easy',
    ARRAY['ACM-W', 'Community', 'Mission']
),
(
    2,
    'ARTIFICIAL INTELLIGENCE',
    'What is the Turing Test designed to evaluate?',
    '["The raw computational clock speed of a processor", "A machine''s ability to exhibit intelligent behavior indistinguishable from a human", "The time complexity and memory overhead of sorting algorithms", "Network bandwidth throughput across distributed clusters"]'::jsonb,
    1,
    'Introduced by Alan Turing in 1950, the Turing Test assesses whether a machine can converse and demonstrate natural language intelligence such that a human evaluator cannot reliably tell it apart from another human.',
    'Easy',
    ARRAY['AI Fundamentals', 'Alan Turing', 'Evaluation']
),
(
    3,
    'COMPUTING HISTORY',
    'Which prestigious annual honor is widely referred to as the "Nobel Prize of Computing"?',
    '["The Fields Medal", "The Pulitzer Award for Technology", "The ACM A.M. Turing Award", "The Von Neumann Pioneer Medal"]'::jsonb,
    2,
    'The ACM A.M. Turing Award is recognized as computing’s highest honor, accompanied by a $1 million prize with financial support provided by Google.',
    'Easy',
    ARRAY['ACM', 'Awards', 'History']
),
(
    4,
    'ARTIFICIAL INTELLIGENCE',
    'Which machine learning paradigm relies on labeled training pairs (input and ground truth target)?',
    '["Unsupervised Learning", "Reinforcement Learning through environment feedback", "Self-Organizing Clustering", "Supervised Learning"]'::jsonb,
    3,
    'Supervised learning algorithms are trained using datasets that include both input features and the corresponding target labels, enabling the model to learn mapping functions for classification or regression.',
    'Medium',
    ARRAY['Machine Learning', 'Supervised Learning']
),
(
    5,
    'ACM-W',
    'What is the primary objective of the ACM-W Scholarship program for student members?',
    '["Enabling female students to attend premier computing research conferences", "Financing campus mainframe server hardware purchases", "Subsidizing undergraduate dorm housing fees", "Purchasing general-purpose software licenses for universities"]'::jsonb,
    0,
    'The ACM-W Scholarship Fund awards scholarships for female undergraduate and graduate students in computer science and related programs to attend research conferences.',
    'Medium',
    ARRAY['ACM-W', 'Scholarships', 'Research']
),
(
    6,
    'ARTIFICIAL INTELLIGENCE',
    'Modern Artificial Neural Networks (ANNs) were conceptually inspired by which biological system?',
    '["Fluid dynamics in circulatory cardiovascular systems", "Interconnected biological neurons and synaptic firing in the human brain", "Photosynthetic chloroplast electron transport chains", "Geological tectonic plate stress distributions"]'::jsonb,
    1,
    'ANNs were initially conceptualized as mathematical models mimicking how biological neurons connect via synapses, activate based on weighted inputs, and learn via plasticity (backpropagation).',
    'Easy',
    ARRAY['Deep Learning', 'Neural Networks']
),
(
    7,
    'ARTIFICIAL INTELLIGENCE',
    'What does the abbreviation "NLP" stand for in modern AI research?',
    '["Non-Linear Programming", "Network Layer Protocol", "Natural Language Processing", "Neural Logical Parsing"]'::jsonb,
    2,
    'Natural Language Processing (NLP) is the interdisciplinary subfield of computer science, artificial intelligence, and linguistics concerned with the interactions between computers and human language.',
    'Easy',
    ARRAY['NLP', 'AI Terminology']
),
(
    8,
    'ARTIFICIAL INTELLIGENCE',
    'Which neural network architecture is the foundational standard for spatial pattern and image recognition?',
    '["Recurrent Feedback Automata", "Binary Decision Forests", "K-Nearest Neighbor Arrays", "Convolutional Neural Networks (CNNs)"]'::jsonb,
    3,
    'Convolutional Neural Networks (CNNs) employ convolutional filter kernels that preserve spatial hierarchies in 2D/3D grids, making them exceptionally suited for computer vision and image classification.',
    'Medium',
    ARRAY['Computer Vision', 'CNN', 'Deep Learning']
),
(
    9,
    'ACM-W',
    'What is the primary role of an ACM-W Student Chapter within an academic institution?',
    '["Fostering peer mentorship, professional development, and technical growth for women in computing", "Auditing departmental course grades and student attendance", "Managing campus bookstore retail operations", "Providing proprietary tech support for university administrative staff"]'::jsonb,
    0,
    'ACM-W Student Chapters serve as on-campus communities that connect students, organize hackathons and tech talks, provide mentorship, and build supportive networks for underrepresented technologists.',
    'Easy',
    ARRAY['ACM-W', 'Student Chapters', 'Mentorship']
),
(
    10,
    'ARTIFICIAL INTELLIGENCE',
    'In machine learning, what does the term "overfitting" describe?',
    '["When a model is too simplistic to capture underlying data relationships (high bias)", "When a model memorizes noise in training data and fails to generalize to unseen test data", "When model weights overflow system memory during distributed tensor gradient descent", "When training convergence occurs too rapidly in fewer than two epochs"]'::jsonb,
    1,
    'Overfitting occurs when a statistical model or neural network aligns too closely with the specific training data points, capturing spurious noise rather than general patterns, which leads to poor test performance.',
    'Medium',
    ARRAY['Machine Learning', 'Model Evaluation', 'Overfitting']
),
(
    11,
    'COMPUTING HISTORY',
    'Why is Ada Lovelace celebrated as the world’s first computer programmer?',
    '["She constructed the physical ENIAC vacuum-tube electronic calculator", "She authored the first published algorithm intended for implementation on Babbage’s Analytical Engine", "She created the original Fortran compiler for IBM in the 1950s", "She proved the theoretical Halting Problem undecidability theorem"]'::jsonb,
    1,
    'In 1843, Ada Lovelace published notes on Charles Babbage’s Analytical Engine that included an algorithm for calculating Bernoulli numbers, recognized today as the first computer algorithm.',
    'Medium',
    ARRAY['Computing History', 'Ada Lovelace', 'Pioneers']
),
(
    12,
    'ETHICS & SOCIETY',
    'Which core principle is explicitly highlighted in the ACM Code of Ethics and Professional Conduct?',
    '["Contributing to society and human well-being while acknowledging all people are stakeholders", "Prioritizing corporate patent monetization over open security vulnerability disclosures", "Restricting technical documentation access strictly to licensed executives", "Maximizing algorithmic compute consumption without environmental regard"]'::jsonb,
    0,
    'Section 1.1 of the ACM Code of Ethics states that computing professionals must contribute to society and human well-being, acknowledging that all people are stakeholders in computing systems.',
    'Medium',
    ARRAY['ACM', 'Ethics', 'Professional Conduct']
)
ON CONFLICT (id) DO UPDATE SET
    category = EXCLUDED.category,
    question = EXCLUDED.question,
    options = EXCLUDED.options,
    correct_index = EXCLUDED.correct_index,
    explanation = EXCLUDED.explanation,
    difficulty = EXCLUDED.difficulty,
    tags = EXCLUDED.tags;

-- ============================================================================
-- 7. Seed Initial Hall of Fame Leaderboard
-- ============================================================================
INSERT INTO public.leaderboard (player_name, avatar_initials, score, accuracy, time_taken_seconds, created_at)
VALUES
('Ada Lovelace', 'AL', 120, 100, 105, timezone('utc'::text, now() - INTERVAL '2 hours')),
('Grace Hopper', 'GH', 110, 92, 132, timezone('utc'::text, now() - INTERVAL '12 hours')),
('Margaret Hamilton', 'MH', 110, 92, 148, timezone('utc'::text, now() - INTERVAL '1 day')),
('Fei-Fei Li', 'FL', 100, 83, 120, timezone('utc'::text, now() - INTERVAL '2 days')),
('Anita Borg', 'AB', 90, 75, 165, timezone('utc'::text, now() - INTERVAL '3 days'));
